GROUP_SYSTEM = "http://terminology.hl7.org/CodeSystem/coverage-class"
GROUP_CODE = "group"
PHONE_SYSTEM = "phone"
EMAIL_SYSTEM = "email"
PATIENT_REFERENCE = "Patient"
EXTENTION_URL = "http://example.org/fhir/StructureDefinition/coverage-priority"
MEDICATION_REFERENCE = "Medication"
INTEND = "order"
STATUS_SYSTEM = "http://terminology.hl7.org/CodeSystem/condition-clinical"
CLASS_DISPLAY = "inpatient encounter"
STATUS = "active"
ENCOUNTER_TYPE_SYSTEM = "http://terminology.hl7.org/CodeSystem/v3-ActCode"
ENCOUNTER_TYPE_CODE = "IMP"
RACE_URL = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race"
ETHNICITY_URL = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity"
HEIGHT_URL = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-height"
WEIGHT_URL = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-weight"
TEXT = "text"
SYSTEM = "urn:oid:2.16.840.1.113883.6.238"
PATIENT_META_URL = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
IDENTIFIER_SYSTEM = "http://example.com/patient"
IDENTIFIER_VALUE = "123456"
TREATMENT_SUMMARY_SYSTEM = "http://terminology.hl7.org/CodeSystem/special-courtesy"
TREATMENT_SUMMARY_CODE = "TREATSUM"
ENCOUNTER_STATUS  = "in-progress"
CLASS_CODE = "IMP"
ENCOUNTER_COURTESY_SYSTEM = "http://terminology.hl7.org/CodeSystem/special-courtesy"
MESSAGE_PATH = "message/custom_message.json"
CURRENT = "Current"
FAMILY = "Family"
OTHER = "Other"
APPOINTMENT_STATUS = "proposed"
PARTICIPANT_STATUS = "accepted"
PRIMARY_STATUS = "Primary"
SECONDARY_STATUS = "Secondary"
TERITORY_STATUS = "Tertiary"
ACTIVE = "active"
COMMUNICATION_CODE = "en-US"
MOBILE = "home"
ALTERNATE_NUMBER = "temp"
RANK_MOBILE = 1
RANK_ALTERNATE = 2
APPOINTMENT_SYSTEM = "http://terminology.hl7.org/CodeSystem/v2-0203"
START_DATE = "1999-01-01"
END_DATE = "2999-12-01"
UPCOMING_APPOINTMENT = "upcoming appointment"
GENDER_MAPPING = {
    "M": "Male",
    "F": "Female",
    "U": "Unknown",
    "O" : "Other"
}
INSURANCE_CONTAINER = "cimparinsurancedatadev"
VISIT_HISTORY_CONTAINER = "cimparvisithistorydatadev"
FILE_SIZE = 5.00
FILE_ETL_HOUR = 1
DELETED = 'deleted'
